name: fefufit_uikit
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:


  flutter:
    sdk: flutter

  theme_tailor: ^2.0.0
  theme_tailor_annotation: ^2.0.0

  loading_animation_widget: ^1.2.0+4
  flutter_svg: ^2.0.9

  balanced_text: ^0.0.3
  top_snackbar_flutter: ^3.1.0


dev_dependencies:


  build_runner: ^2.4.6

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  assets:
    - assets/icons/
    